# Generated by Django 3.2.3 on 2021-05-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proHub', '0003_auto_20210529_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proHub.profile'),
        ),
    ]
