# Generated by Django 3.2.3 on 2021-05-29 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proHub', '0005_rename_location_profile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('usability', models.FloatField(default=0.0, null=True)),
                ('design', models.FloatField(default=0.0, null=True)),
                ('creativity', models.FloatField(default=0.0, null=True)),
                ('content', models.FloatField(default=0.0, null=True)),
                ('mobile', models.FloatField(default=0.0, null=True)),
                ('usability_average', models.FloatField(default=0.0, null=True)),
                ('design_average', models.FloatField(default=0.0, null=True)),
                ('creativity_average', models.FloatField(default=0.0, null=True)),
                ('content_average', models.FloatField(default=0.0, null=True)),
                ('mobile_average', models.FloatField(default=0.0, null=True)),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='proHub.projects')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proHub.profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
