# Generated by Django 3.2.3 on 2021-05-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proHub', '0006_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='urls',
            new_name='url',
        ),
    ]
