# Generated by Django 3.2.3 on 2021-05-30 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proHub', '0007_rename_urls_projects_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Project description length has to be more than 200', regex='^.{200}$')]),
        ),
    ]
