# Generated by Django 3.2.3 on 2021-05-30 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proHub', '0008_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(200)]),
        ),
    ]
