# Generated by Django 3.2.3 on 2021-05-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proHub', '0011_auto_20210530_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_photos/'),
        ),
    ]
