# Generated by Django 3.2.3 on 2021-05-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proHub', '0012_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_photos/default_qbeyia', upload_to='profile_photos/'),
        ),
    ]
