# Generated by Django 3.2.3 on 2021-05-31 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proHub', '0016_rename_image_comment_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content_average',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='creativity_average',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='design_average',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='mobile_average',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='usability_average',
        ),
    ]
