# Generated by Django 3.2.3 on 2021-05-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proHub', '0017_auto_20210601_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='projects',
            new_name='project',
        ),
    ]
