# Generated by Django 3.2.3 on 2021-05-31 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proHub', '0018_rename_projects_rating_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='reviewer',
        ),
    ]
