# Generated by Django 3.2.3 on 2021-06-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proHub', '0019_remove_rating_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='voters',
        ),
    ]
